source "https://rubygems.org"

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'pry'
gem 'rest-client'
gem 'awesome_print'
# gem 'tco'
# gem 'rmagick', '~> 3.2'
# gem 'catpix'
gem 'mini_magick'
gem 'bcrypt', '~> 3.1.7'
gem 'tty-prompt'

#gem 'password'
#gem 'open3'
#gem 'optionparser'