source "https://rubygems.org"

gem 'bundler', :require => nil
gem 'rubygems-update', :require => nil

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'pry'
gem 'rest-client'
gem 'awesome_print'
gem 'tco'
# gem 'rmagick'
gem 'catpix'
gem 'mini_magick'
gem 'bcrypt', '~> 3.1.7'
gem 'tty-prompt'
gem 'twitter'
gem 't'
gem 'dotenv'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'pastel'
gem 'tty-box'
gem 'launchy'
# gem 'image_optimizer'
# gem 'password'
# gem 'open3'
# gem 'optionparser'